version: '3.8'

services:
  backend:
    build:
      context: .  # Path to the backend directory
      dockerfile: Dockerfile
    container_name: nyt-rss-backend
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080

  frontend:
    build:
      context: ../nyt-rss-frontend  # Path to the frontend directory
      dockerfile: Dockerfile
    container_name: nyt-rss-frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    environment:
      - BACKEND_HOST=backend
    volumes:
      - ../nyt-rss-frontend:/app  # Path to the frontend directory: Mounting the frontend directory
      - /app/node_modules
    depends_on:
      - backend
